# Image
# FROM node:current-alpine
# FROM node:latest
FROM node:15.14.0-buster

# Set up work directory
WORKDIR /var/www/client

# Configure host
# ENV HOST 0.0.0.0
# ENV NUXT_HOST=0.0.0.0

# Init command
# CMD ["bash", "-c", "while :; do echo 'Hit CTRL+C'; sleep 60; done"]
# CMD ["bash", "-c", "yarn && yarn dev"]
# CMD ["bash", "-c", "yarn dev"]